sudo: required

language: go

go:
  - "1.8"
  - "1.9"
  - "1.12.1"

install:
  - "sudo apt-get update"
  - "sudo apt-get install -y libpcap-dev"

before_script:
  - "go get -u github.com/golang/dep/cmd/dep"
  - "go get -u github.com/google/gopacket"
  - "dep ensure"

script:
  - "go test -v"
